#!/usr/bin/env sh

GPU_PATH="/sys/class/drm/card1/device/pp_power_profile_mode"

profile="${1}"

error() {
	echo "error: ${1}"
	echo
}

help() {
	echo "usage:"
	echo "    setprof <profile>"
	echo
	echo "profiles:"
	echo "    3d         for generic 3d rendering"
	echo "    compute    for cpu/gpu computing"
	echo "    idle       for power saving"
	echo "    vr         for vr rendering"
}

if [ -z "${profile}" ]
then
	error "missing profile"
	help

	exit 2
fi

if [ "${profile}" = "3d" ]
then
	# Set CPU profile.
	powerprofilesctl set performance

	# Set GPU profile.
	echo -n "1" > "${GPU_PATH}"
elif [ "${profile}" = "compute" ]
then
	# Set CPU profile.
	powerprofilesctl set performance

	# Set GPU profile.
	echo -n "5" > "${GPU_PATH}"
elif [ "${profile}" = "idle" ]
then
	# Set CPU profile.
	powerprofilesctl set power-saver

	# Set GPU profile.
	echo -n "2" > "${GPU_PATH}"
elif [ "${profile}" = "vr" ]
then
	# Set CPU profile.
	powerprofilesctl set performance

	# Set GPU profile.
	echo -n "4" > "${GPU_PATH}"
else
	error "unknown profile \`${profile}\`"
	help

	exit 2
fi
